config/routes.rb
Rails.application.routes.draw do
  root 'statics#home'
  resources :students
  resources :courses
  resources :classrooms
end

app/models/classroom.rb
class Classroom < ActiveRecord::Base
  belongs_to :student
  belongs_to :course

  validates :student_id, presence: true
  validates :course_id, presence: true, uniqueness: { scope: :student_id }
end

app/models/course.rb
class Course < ActiveRecord::Base
  has_many :classrooms, dependent: :destroy
  has_many :students, through: :classrooms
 
  validates :name, presence: true, uniqueness: true
  validates :description, presence: true
  validates :status, numericality: { only_integer: true }, allow_blank: true

  def to_s
    name
  end
end

app/models/student.rb
class Student < ActiveRecord::Base
  has_many :classrooms, dependent: :destroy
  has_many :courses, through: :classrooms

  validates :name, presence: true
  validates :register_number, presence: true, uniqueness: true
  validates :status, numericality: { only_integer: true }, allow_blank: true

  def to_s
    "#{name} – #{register_number}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/base_controller.rb
class BaseController < ApplicationController
  before_action :find_model, only: [:show, :update, :edit, :destroy]

  def index
    @models = model_class.all
  end

  def new
    @model = model_class.new
  end

  def create
    @model = model_class.new(model_params)
    if @model.save
      flash[:success] = "#{model_class.model_name.human} criado com sucesso!"
      redirect_to url_for(model_class)
    else
      flash[:danger] = "Não foi possível criar o #{model_class.model_name.human}, veja os erros abaixo!"
      render :new
    end
  end

  def edit
  end

  def update
    if @model.update(model_params)
      flash[:success] = "#{model_class.model_name.human} alterado com sucesso!"
      redirect_to url_for(model_class)
    else
      flash[:danger] = "Não foi possível alterar o #{model_class.model_name.human}, veja os erros abaixo!"
      render :edit
    end
  end

  def destroy
    @model.destroy!
    flash[:success] = "#{model_class.model_name.human} excluído com sucesso!"
    redirect_to url_for(model_class)
  end

  def show
  end

  private
    def find_model
      @model = model_class.find(params[:id])
    end
end

app/controllers/concerns/classrooms_controller.rb
class ClassroomsController < BaseController
  before_action :find_model, only: [:destroy]

  # index, new, create, and destroy from BaseController

  def edit
    redirect_to classrooms_path
  end

  def update
    redirect_to classrooms_path
  end

  private

    def model_class
      Classroom
    end

    def model_params
      params.require(:classroom).permit(:student_id, :course_id)
    end
end

app/controllers/courses_controller.rb
class CoursesController < BaseController

  #index, new, create, edit, update, and destroy from BaseController

  private
    def model_class
      Course
    end

    def model_params
      params.require(:course).permit(:name, :description)
    end
end

app/controllers/statics_controller.rb
class StaticsController < ApplicationController
  def home 
  end
end

app/controllers/students_controller.rb
class StudentsController < BaseController
  #index, new, create, edit, update, and destroy from BaseController

  private
    def model_class
      Student
    end

    def model_params
      params.require(:student).permit(:name, :register_number)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def show_link(object)
    link_to 'Detalhes', object
  end

  def delete_link(object)
    link_to 'Excluir', object, method: :delete, data: {
      confirm: "A exclusão de um #{model_name(object)} é irreversível! Você tem certeza que deseja excluir o #{model_name(object)} '#{object.name}'? As matrículas relacionadas serão apagadas."
    }
  end

  def back_button(klass)
    link_to 'Voltar', klass, class: 'btn btn-default'
  end

  private
    def model_name(object)
      object.class.model_name.human.downcase
    end
end

app/helpers/classroom_helper.rb
module ClassroomHelper
  def extra_student_id_class(classroom)
    'has-error' if classroom.errors[:student_id].present?
  end

  def extra_course_id_class(classroom)
    'has-error' if classroom.errors[:course_id].present?
  end
end

app/helpers/course_helper.rb
module CourseHelper
  def edit_course_link(course)
    link_to 'Alterar', edit_course_path(course)
  end

  def action_course_links(course)
    [show_link(course), edit_course_link(course), delete_link(course)].join(' | ').html_safe
  end
end

app/helpers/flash_helper.rb
module FlashHelper
  def flash_messages
    flash.collect do |key, msg|
      alert_class = case(key)
      when :notice
        "success"
      when :alert
        "error"
      else
        "info"
      end

      content_tag(:div, msg, :id => key, :class => "alert #{alert_class} center flash-message")
    end.join.html_safe
  end
end

app/helpers/student_helper.rb
module StudentHelper
  def edit_student_link(student)
    link_to 'Alterar', edit_student_url(student)
  end

  def action_student_links(student)
    [show_link(student), edit_student_link(student), delete_link(student)].join(' | ').html_safe
  end
end

app/helpers/translation_helper.rb
module TranslationHelper
  # Translate model name
  #
  #   <%= tm Post %>
  #   ...
  #   <%= tm Post, 2 %>
  #
  def translate_model_name(model, count = 1)
    model.model_name.human(:count => count)
  end
  alias_method :tm, :translate_model_name

  # Translate model name pluralized
  #
  #   <%= tm Post %>
  #
  def translate_model_name_pluralized(model)
    translate_model_name(model, count = 2)
  end
  alias_method :tmp, :translate_model_name_pluralized

  # Translate a model attribute from config/locales/models-*.yml for more details.
  #
  #   <%= ta Post, :title %>
  #   ...
  #   <%= ta Post, :title, 2 %>
  #
  def translate_model_attribute(model, attribute, count = 1)
    model.human_attribute_name(attribute, :count => count)
  end
  alias_method :ta, :translate_model_attribute
end

app/views/classrooms/_form.html.haml
= simple_form_for [classroom] do |f|
  .panel.panel-default
    .panel-heading
      %h3.panel-title Informações do Estudante
    .panel-body
      .row
        .col-md-6.form-group{class: extra_student_id_class(classroom)}
          = f.label :student_id
          .select2
            = collection_select(:classroom, :student_id, Student.all, :id, :to_s, {prompt: true, selected: classroom.student_id}, {class: "form-control required"})
          = f.error :student_id
        .col-md-6.form-group{class: extra_course_id_class(classroom)}
          = f.label :course_id
          .select2
            = collection_select(:classroom, :course_id, Course.all, :id, :to_s, {prompt: true, selected: classroom.course_id}, {class: "form-control required"})
          = f.error :course_id
  = back_button(Classroom)
  = f.submit 'Salvar', class: "btn btn-success pull-right"

app/views/classrooms/index.html.haml
%table.table.table-hover
  %thead
    %tr
      %th= Classroom.human_attribute_name(:id)
      %th= Classroom.human_attribute_name(:student_id)
      %th= Classroom.human_attribute_name(:course_id)
      %th= Classroom.human_attribute_name(:created_at)
      %th.col-md-2 
        Ação
  %tbody
    - @models.each do |classroom|
      %tr
        %th= classroom.id
        %th= classroom.student
        %th= classroom.course
        %th= I18n.l(classroom.created_at)
        %th.col-md-2
          = link_to 'Excluir', classroom, method: :delete, data: {confirm: "A exclusão de uma matrícula é irreversível! Você tem certeza que deseja excluir essa matrícula?"}

.container-fluid.form-end
  %a.btn.btn-success.pull-right{href: new_classroom_path}
    Nova Matrícula

app/views/classrooms/new.html.haml
%h4
  Nova Matrícula
= render partial: 'form', locals: {classroom: @model}

app/views/courses/_courses.html.haml
%table.table.table-hover
  %thead
    %tr
      %th= Course.human_attribute_name(:id)
      %th= Course.human_attribute_name(:name)
      %th= Course.human_attribute_name(:description)
      %th.col-md-2 
        Ações
  %tbody
    - courses.each do |course|
      %tr
        %th= course.id
        %th= course.name
        %th= course.description
        %th.col-md-3
          = action_course_links(course)

app/views/courses/_form.html.haml
= simple_form_for [course] do |f|
  .panel.panel-default
    .panel-heading
      %h3.panel-title Informações do Curso
    .panel-body
      .row
        .col-md-4.form-group
          = f.input :name, input_html: {class: "form-control"}
        .col-md-8.form-group
          = f.input :description, input_html: {class: "form-control"}
  = back_button(Course)
  = f.submit 'Salvar', class: "btn btn-success pull-right"

app/views/courses/edit.html.haml
%h4
  Editar Curso
= render partial: 'form', locals: {course: @model}

app/views/courses/index.html.haml
= render partial: 'courses', locals: {courses: @models}

.container-fluid.form-end
  %a.btn.btn-success.pull-right{href: new_course_path}
    Novo Curso

app/views/courses/new.html.haml
%h4
  Novo Curso
= render partial: 'form', locals: {course: @model}

app/views/courses/show.html.haml
%h3
  = Course.model_name.human
.row
  .col-md-2
    %label
      = Course.human_attribute_name(:id)
  .col-md-10
    = @model.id
.row
  .col-md-2
    %label
      = Course.human_attribute_name(:name)
  .col-md-10
    = @model.name
.row
  .col-md-2
    %label
      = Course.human_attribute_name(:description)
  .col-md-10
    = @model.description
.row
  .col-md-2
    %label
      Ações
  .col-md-10
    = action_course_links(@model)

%hr

%h4
  Estudantes do Curso
= render partial: 'students/students', locals: {students: @model.students}

= back_button(Course)

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title ProficiencyTest
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body{"data-controller"=> controller.controller_name, "data-action" => controller.action_name}
    %header#header
      %nav.navbar.navbar-default.navbar-client.center-align{role: :navigation}
        .container.center-align
          %ul.nav.navbar-nav.navbar-right
            %li#statics
              = link_to 'Home', root_path
            %li#courses
              = link_to Course.model_name.human.pluralize, courses_path
            %li#students
              = link_to Student.model_name.human.pluralize, students_path
            %li#classrooms
              = link_to Classroom.model_name.human.pluralize, classrooms_path
    %section#content.container
      .flash
        - flash.each do |name, msg|
          .alert{class: "alert-#{name}"}
            %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", type: :button}
              &times;
            = content_tag :div, msg
      = yield

app/views/statics/home.html.haml
%h3
  Bem Vindo!
%h4
  Utilize o menu no topo da página para navegar no sistema.

app/views/students/_form.html.haml
= simple_form_for [student] do |f|
  .panel.panel-default
    .panel-heading
      %h3.panel-title Informações do Estudante
    .panel-body
      .row
        .col-md-8.form-group
          = f.input :name, input_html: {class: "form-control"}
        .col-md-4.form-group
          = f.input :register_number, input_html: {class: "form-control"}
  = back_button(Student)
  = f.submit 'Salvar', class: "btn btn-success pull-right"

app/views/students/_students.html.haml
%table.table.table-hover
  %thead
    %tr
      %th= Student.human_attribute_name(:id)
      %th= Student.human_attribute_name(:name)
      %th= Student.human_attribute_name(:register_number)
      %th.col-md-2 
        Ações
  %tbody
    - students.each do |student|
      %tr
        %th= student.id
        %th= student.name
        %th= student.register_number
        %th.col-md-3
          = action_student_links(student)

app/views/students/edit.html.haml
%h4
  Editar Estudante
= render partial: 'form', locals: {student: @model}

app/views/students/index.html.haml
= render partial: 'students', locals: {students: @models}

.container-fluid.form-end
  %a.btn.btn-success.pull-right{href: new_student_path}
    Novo Estudante

app/views/students/new.html.haml
%h4
  Novo Estudante
= render partial: 'form', locals: {student: @model}

app/views/students/show.html.haml
%h3
  = Student.model_name.human
.row
  .col-md-2
    %label
      = Student.human_attribute_name(:id)
  .col-md-10
    = @model.id
.row
  .col-md-2
    %label
      = Student.human_attribute_name(:name)
  .col-md-10
    = @model.name
.row
  .col-md-2
    %label
      = Student.human_attribute_name(:register_number)
  .col-md-10
    = @model.register_number
.row
  .col-md-2
    %label
      Ações
  .col-md-10
    = action_student_links(@model)

%hr

%h4
  Cursos do Estudante
= render partial: 'courses/courses', locals: {courses: @model.courses}

= back_button(Student)